"""empty message

Revision ID: 2c42836b2803
Revises: 69523adae47c
Create Date: 2020-03-08 01:00:26.139255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c42836b2803'
down_revision = '69523adae47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Universidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(), nullable=True),
    sa.Column('nick', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Usuarios_email'), 'Usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_Usuarios_nick'), 'Usuarios', ['nick'], unique=True)
    op.drop_table('universidad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universidad',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creado', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modificado', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modificado_por', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='universidad_pkey')
    )
    op.drop_index(op.f('ix_Usuarios_nick'), table_name='Usuarios')
    op.drop_index(op.f('ix_Usuarios_email'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_table('Universidades')
    # ### end Alembic commands ###
