"""empty message

Revision ID: 69523adae47c
Revises: c4c0557d7d85
Create Date: 2020-03-07 01:50:06.699983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69523adae47c'
down_revision = 'c4c0557d7d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('entity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creado', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modificado', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modificado_por', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='entity_pkey')
    )
    op.drop_table('universidad')
    # ### end Alembic commands ###
